version: '3'
services:
    client:
        build: 
            dockerfile: Dockerfile
            context: ./client 
        image: client:1.0
   #        volumes:
   #     - /app/node_modules 
   #        - ./server:/app
    comments:
        restart: always
        build: 
          dockerfile: Dockerfile
          context: ./comments
        image: comments:1.0
     #    ports: 
    #     - '5000:80'
    event_bus: 
        build: 
            dockerfile: Dockerfile
            context: ./event_bus
        image: event_bus:1.0
     #    volumes:
     #      - /app/node_modules 
     #      - ./client:/app
    moderator: 
        build: 
            dockerfile: Dockerfile
            context: ./moderator
        image: moderator:1.0
    post: 
        build: 
            dockerfile: Dockerfile
            context: ./posts
        image: post:1.0

    query: 
        build: 
            dockerfile: Dockerfile
            context: ./query
        image: query:1.0
