version: '3'
services:
    client:
        build: 
            dockerfile: Dockerfile
            context: ./client 
        image: client
   #        volumes:
   #     - /app/node_modules 
   #        - ./server:/app
    comments:
        restart: always
        build: 
          dockerfile: Dockerfile
          context: ./comments
        image: comments
     #    ports: 
    #     - '5000:80'
    event_bus: 
        build: 
            dockerfile: Dockerfile
            context: ./event_bus
        image: event_bus
     #    volumes:
     #      - /app/node_modules 
     #      - ./client:/app
    moderator: 
        build: 
            dockerfile: Dockerfile
            context: ./moderator
        image: moderator
    post: 
        build: 
            dockerfile: Dockerfile
            context: ./posts
        image: post

    query: 
        build: 
            dockerfile: Dockerfile
            context: ./query
        image: query
