apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: post-dep
  name: post-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: post-dep
status:
  loadBalancer: {}