apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: event-bus-dep
  name: event-bus-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: event-bus-dep
status:
  loadBalancer: {}