apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: comments-dep
  name: comments-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: comments-dep
    spec:
      containers:
      - image: mohcontreg.azurecr.io/comments
        name: comments
        resources: {}
status: {}
