apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-dep
  name: client-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-dep
    spec:
      containers:
      - image: mohcontreg.azurecr.io/client
        name: client
        resources: {}
status: {}
